config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#index'
  resources :student_details
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student_detail.rb
class StudentDetail < ApplicationRecord
  validates :student_name, presence: true
  validates :roll_no, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @student_details = StudentDetail.all
  end
end

app/controllers/student_details_controller.rb
class StudentDetailsController < ApplicationController
  before_action :fetch_id, only: [:edit, :destroy, :show, :update]

  def index
    @student_details = StudentDetail.all
  end

  def new
    @student_detail = StudentDetail.new
  end

  def create
    @student_detail = StudentDetail.new(student_details_params)
    if @student_detail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student_detail.update(student_details_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @student_detail.destroy
      redirect_to root_path
    else
      flash[:alert] = 'error while deleting student_details'
    end
  end

  def fetch_id
    @student_detail = StudentDetail.find(params[:id])
  end

  private

  def student_details_params
    params.require(:student_detail).permit(:student_name, :gender, :roll_no, :address, :university_name)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/student_details_helper.rb
module StudentDetailsHelper
end

app/views/homes/index.html.erb
<h1><center>Welcome</center></h1>
<button type="button" class="btn btn-dark"> 
<%= link_to 'New Student',new_student_detail_path %>
</button>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<br/>
<% @student_details.each do |sd| %>
  <%= sd.student_name %>
  <%= sd.roll_no %>
  <%= sd.address %>
  <%= sd.university_name %>
  <%= link_to 'Edit Student', edit_student_detail_path(sd) %>
  <%= link_to "Destroy", student_detail_path(sd),method: :delete,data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/student_details/_form.html.erb
<%= form_for @student_detail do |f| %>

  <%= f.label :student_name %>
  <%= f.text_field :student_name %>
  <br/>

  <%= f.label :roll_no %>
  <%= f.number_field :roll_no %>
  <br/>

  <%= f.label :gender %>
  <%= f.select :gender, %w{Male Female}, :prompt => 'Select', required: true, placeholder: 'Gender' %>
  <br/>

  <%= f.label :address %>
  <%= f.text_area :address %>
  <br/>

  <%= f.label :university_name %>
  <%= f.text_field :university_name %>
  <br/>

  <%= f.submit %>

<% end %>

app/views/student_details/edit.html.erb
<%= render partial: 'form' %>

app/views/student_details/index.html.erb
<h1>StudentDetails#index</h1>
<p>Find me in app/views/student_details/index.html.erb</p>

app/views/student_details/new.html.erb
<%= render partial: 'form' %>

app/views/student_details/show.html.erb
<h1>StudentDetails#show</h1>
<p>Find me in app/views/student_details/show.html.erb</p>